version: '3.2'


services:
  back:
    container_name: back-end
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    volumes:
      - ./back-end/:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
#      - NODE_ENV=${NODE_ENV:?err} for making env mandatory
      - NODE_ENV=${NODE_ENV}
      - DB_CON_STR=${DB_CON_STR}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CHOKIDAR_USEPOLLING=true
  front:
    container_name: front-end
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
      - /usr/app/build
    depends_on:
      - back
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${CLIENT_PORT}

  mongo:
    image: mongo:3.6.1
    ports:
      - 27017:27017
    restart: always
    command: --smallfiles
    container_name: app_mongodb_c
    volumes:
      - ~/dockerdata/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example